### ISSUE TITLE
Cannot decompress 这是中文，压缩后不能解压

### ISSUE THREAD

**Issue by easykoala** [Datamart/lzw-compressor#1]
let plText= "aaaaaaaa这是中文，压缩后不能解压bbbbbbbbbb";
plText = compress(plText);
console.log(plText) //aĀāĀ这是中文，压缩后不能解压bĐđĒ

plText = decompress(plText);
console.log(plText);  //aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbb

**Comment by vpodk** [comment]
@easykoala, thanks for the great catch.
At the moment, you can compress and decompress Chinese only this way:

```js
unescape(decompress(compress(escape("aaaaaaaa这是中文，压缩后不能解压bbbbbbbbbb"))));
decodeURIComponent(decompress(compress(encodeURIComponent("aaaaaaaa这是中文，压缩后不能解压bbbbbbbbbb"))))
```
